# Generated by Django 5.2.3 on 2025-06-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_qr_code_complaint_location_lostandfound'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
