# Generated by Django 5.2.3 on 2025-06-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_route_route_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_no',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
