# Generated by Django 5.2.3 on 2025-06-24 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_route_route_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='contact_number',
            field=models.CharField(default='unknown', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lost_and_found/'),
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='loss_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='passenger_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.route'),
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
