# Generated by Django 5.2.3 on 2025-07-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_busstop_routestop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
