# Generated by Django 5.2.3 on 2025-07-04 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_booking_schedule_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.route'),
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
