# Generated by Django 5.2.3 on 2025-07-04 20:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_booking_destination_booking_route_booking_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=100, null=True, verbose_name=core.models.Route),
        ),
        migrations.AlterField(
            model_name='booking',
            name='source',
            field=models.CharField(max_length=100, null=True, verbose_name=core.models.Route),
        ),
    ]
