# Generated by Django 5.2.3 on 2025-07-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_booking_destination_alter_booking_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='route',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
