# Generated by Django 5.2.3 on 2025-07-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_booking_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by_conductor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='verified_by_conductor',
            field=models.BooleanField(default=False),
        ),
    ]
