# Generated by Django 5.2.3 on 2025-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_booking_created_by_conductor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
