# Generated by Django 5.2.3 on 2025-07-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_booking_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_online',
            field=models.BooleanField(default=False),
        ),
    ]
