# Generated by Django 5.2.3 on 2025-10-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
