# Generated by Django 5.2.3 on 2025-10-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_schedule_departure_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('bus', 'route', 'departure_time')},
        ),
    ]
