# Generated by Django 5.2.3 on 2025-10-16 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor_service', '0001_initial'),
        ('core', '0021_alter_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='core.bus')),
            ],
        ),
    ]
