# Generated by Django 5.2.3 on 2025-10-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor_service', '0002_buslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conductorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='conductor_profiles/'),
        ),
    ]
