# Generated by Django 5.2.3 on 2025-10-16 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor_service', '0003_conductorprofile_license_number_and_more'),
        ('core', '0021_alter_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bus')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conductor_service.conductorprofile')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.schedule')),
            ],
        ),
    ]
